language: smalltalk
sudo: false

# services: mongodb

# Select operating system(s)
os:
  - linux
# random SSL error with iceberg  - osx

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo64-9.0
  
# default config: .smalltalk.ston (client)
#matrix:
#  include: 
#    - smalltalk_config: .server.ston
#    - smalltalk_config: .failingTests.ston
#  allow_failures: 
#    - smalltalk_config: .failingTests.ston

# configuration
before_script:
  - git config --global user.name 'Travis CI'
  - git config --global user.email 'pakbot-ci@travis-ci.org'
